package com.api.naver.smartstore.service.template.response.ProductOrders.embedded;

import lombok.Data;

@Data
public class ProductOrder {
    private String claimStatus;
    private String claimType;
    private String decisionDate;
    private String delayedDispatchDetailedReason;
    private String delayedDispatchReason;
    private String deliveryDiscountAmount;
    private String deliveryFeeAmount;
    private String deliveryPolicyType;
    private String expectedDeliveryMethod;
    private String freeGift;
    private String mallId;
    private String optionCode;
    private String optionPrice;
    private String packageNumber;
    private String placeOrderDate;
    private String placeOrderStatus;
    private String productClass;
    private String productDiscountAmount;
    private String productId;
    private String productName;
    private String productOption;
    private String productOrderId;
    private String productOrderStatus;
    private String quantity;
    private String sectionDeliveryFee;
    private String sellerProductCode;
    private CollectAddress shoppingAddress;
    private String shippingDueDate;
    private String shippingFeeType;
    private String shippingMemo;
    private CollectAddress takingAddress;
    private String totalPaymentAmount;
    private String totalProductAmount;
    private String unitPrice;
    private String sellerBurdenDiscountAmount;
    private String commissionRatingType;
    private String commissionPrePayStatus;
    private String paymentCommission;
    private String saleCommission;
    private String expectedSettlementAmount;
    private String inflowPath;
    private String itemNo;
    private String optionManageCode;
    private String sellerCustomCode1;
    private String sellerCustomCode2;
    private String claimId;
    private String channelCommission;
    private String individualCustomUniqueCode;
    private Integer productImediateDiscountAmount;
    private Integer productProductDiscountAmount;
    private Integer productMultiplePurchaseDiscountAmount;
    private Integer sellerBurdenImediateDiscountAmount;
    private Integer sellerBurdenProductDiscountAmount;
    private Integer sellerBurdenMultiplePurchaseDiscountAmount;
    private Integer knowledgeShoppingSellingInterlockCommission;
    private String giftReceivingStatus;
    private Integer sellerBurdenStoreDiscountAmount;
    private String sellerBurdenMultiplePurchaseDiscountType;
    private String logisticsCompanyId;
    private String logisticsCenterId;
    private HopeDelivery hopeDelivery;
    private String arrivalGuaranteeDate;
    private String deliveryAttributeType;
}
